# Generated by Django 4.1.7 on 2023-03-24 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examsolution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardSubTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ExamBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_board', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('exam_board_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examsolution.examboard')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(max_length=200)),
                ('question_directory', models.FileField(null=True, upload_to='')),
                ('answer_name', models.CharField(max_length=200)),
                ('answer_directory', models.FileField(null=True, upload_to='')),
                ('detailed_answer_link', models.CharField(blank=True, max_length=500, null=True)),
                ('video_explanation_link', models.CharField(blank=True, max_length=500, null=True)),
                ('board_sub_topic_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examsolution.boardsubtopic')),
                ('session_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examsolution.session')),
                ('year_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examsolution.year')),
            ],
        ),
        migrations.CreateModel(
            name='FullQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_question_name', models.CharField(max_length=200)),
                ('full_question_link', models.CharField(max_length=500)),
                ('full_answersheet_name', models.CharField(max_length=200)),
                ('full_answersheet_link', models.CharField(max_length=500)),
                ('session_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examsolution.session')),
                ('subject_key', models.ForeignKey(null='False', on_delete=django.db.models.deletion.CASCADE, to='examsolution.subject')),
                ('year_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examsolution.year')),
            ],
        ),
        migrations.AddField(
            model_name='boardsubtopic',
            name='paper_num_key',
            field=models.ForeignKey(null='False', on_delete=django.db.models.deletion.CASCADE, to='examsolution.paper'),
        ),
        migrations.AddField(
            model_name='boardsubtopic',
            name='subject_key',
            field=models.ForeignKey(null='False', on_delete=django.db.models.deletion.CASCADE, to='examsolution.subject'),
        ),
    ]
