# Generated by Django 4.1.7 on 2023-03-30 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examsolution', '0003_searchstuff'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SearchStuff',
            new_name='SearchedItems',
        ),
        migrations.RenameField(
            model_name='searcheditems',
            old_name='search_text',
            new_name='search_stuff',
        ),
    ]
