# Generated by Django 4.1.7 on 2023-04-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examsolution', '0004_rename_searchstuff_searcheditems_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchedItems',
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='exam_report_comment',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
