# Generated by Django 4.1.7 on 2023-05-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examsolution', '0005_delete_searcheditems_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswer',
            name='board_sub_topic_key',
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='board_sub_topic_key',
            field=models.ManyToManyField(to='examsolution.boardsubtopic'),
        ),
    ]
