# Generated by Django 4.1.7 on 2023-05-10 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examsolution', '0006_remove_questionanswer_board_sub_topic_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswer',
            name='board_sub_topic_key',
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='board_sub_topic_key',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='examsolution.boardsubtopic'),
            preserve_default=False,
        ),
    ]
