# Generated by Django 4.1.7 on 2023-05-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examsolution', '0008_alter_questionanswer_answer_directory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='exam_report_comment',
            field=models.CharField(blank=True, max_length=20000),
        ),
    ]
