# Generated by Django 4.1.7 on 2023-05-13 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examsolution', '0009_alter_questionanswer_exam_report_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fullquestionanswer',
            old_name='full_answersheet_link',
            new_name='full_answersheet_directory',
        ),
        migrations.RenameField(
            model_name='fullquestionanswer',
            old_name='full_question_link',
            new_name='full_question_directory',
        ),
        migrations.CreateModel(
            name='ReportThreshPrep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_name', models.CharField(max_length=500)),
                ('extra_directory', models.CharField(max_length=500)),
                ('session_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examsolution.session')),
                ('subject_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examsolution.subject')),
                ('year_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examsolution.year')),
            ],
        ),
    ]
