# Generated by Django 4.1.7 on 2023-05-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examsolution', '0010_rename_full_answersheet_link_fullquestionanswer_full_answersheet_directory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullquestionanswer',
            name='full_answersheet_directory',
            field=models.FileField(null=True, upload_to='FullMarkScheme'),
        ),
        migrations.AlterField(
            model_name='fullquestionanswer',
            name='full_question_directory',
            field=models.FileField(null=True, upload_to='FullQuestionPaper'),
        ),
    ]
