# Generated by Django 4.1.7 on 2023-05-14 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examsolution', '0011_alter_fullquestionanswer_full_answersheet_directory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullquestionanswer',
            name='paper_number',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='examsolution.paper'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportthreshprep',
            name='extra_directory',
            field=models.FileField(null=True, upload_to='ReportThreshPrep'),
        ),
    ]
