# Generated by Django 4.1.7 on 2023-05-14 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examsolution', '0014_alter_fullquestionanswer_paper_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PossibleLetters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PossibleQuestionNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PaperOneAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_category', models.CharField(max_length=500, null=True)),
                ('question_examreportcmt', models.CharField(max_length=20000, null=True)),
                ('question_video_explanation', models.URLField(max_length=1000, null=True)),
                ('paper_one_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examsolution.fullquestionanswer')),
                ('question_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examsolution.possibleletters')),
                ('question_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examsolution.possiblequestionnumber')),
            ],
        ),
    ]
