# Generated by Django 4.1.7 on 2023-05-14 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examsolution', '0015_possibleletters_possiblequestionnumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paperoneanswers',
            old_name='paper_one_name',
            new_name='paper_one_name_key',
        ),
        migrations.RenameField(
            model_name='paperoneanswers',
            old_name='question_answer',
            new_name='question_answer_key',
        ),
        migrations.RenameField(
            model_name='paperoneanswers',
            old_name='question_number',
            new_name='question_number_key',
        ),
    ]
