# Generated by Django 4.1.7 on 2023-05-19 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examsolution', '0016_rename_paper_one_name_paperoneanswers_paper_one_name_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='website_pics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_logo', models.ImageField(null=True, upload_to='WesbitePics')),
            ],
        ),
        migrations.AlterField(
            model_name='fullquestionanswer',
            name='paper_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='examsolution.paper'),
        ),
        migrations.AlterField(
            model_name='paperoneanswers',
            name='question_category',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='paperoneanswers',
            name='question_examreportcmt',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='paperoneanswers',
            name='question_video_explanation',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
