# Generated by Django 4.1.7 on 2023-05-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examsolution', '0017_website_pics_alter_fullquestionanswer_paper_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='home_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_logo', models.ImageField(null=True, upload_to='WesbitePics')),
            ],
        ),
    ]
