# Generated by Django 4.1.7 on 2022-01-01 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examsolution', '0018_home_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullquestionanswer',
            name='A_raw_mark_req',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fullquestionanswer',
            name='B_raw_mar_req',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fullquestionanswer',
            name='C_raw_mar_req',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fullquestionanswer',
            name='D_raw_mar_req',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fullquestionanswer',
            name='E_raw_mar_req',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
