# Generated by Django 4.1.7 on 2023-06-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examsolution', '0020_fullquestionanswer_general_exam_report_cmnt'),
    ]

    operations = [
        migrations.CreateModel(
            name='people_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_pic', models.CharField(max_length=2000)),
                ('picture', models.ImageField(null=True, upload_to='WesbitePics')),
            ],
        ),
    ]
