# Generated by Django 4.1.7 on 2023-06-09 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examsolution', '0022_usertask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['subject']},
        ),
    ]
