# Generated by Django 4.1.7 on 2023-06-09 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('examsolution', '0023_alter_subject_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgressRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_written', models.CharField(max_length=200)),
                ('raw_mark', models.IntegerField()),
                ('percentage', models.IntegerField()),
                ('letter_grade', models.CharField(max_length=200)),
                ('hours_taken', models.IntegerField(blank=True, null=True)),
                ('minutes_taken', models.IntegerField(blank=True, null=True)),
                ('questions_failed', models.CharField(blank=True, max_length=2000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
