# Generated by Django 4.1.7 on 2023-06-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examsolution', '0024_userprogressrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogressrecord',
            name='hours_taken',
        ),
        migrations.RemoveField(
            model_name='userprogressrecord',
            name='letter_grade',
        ),
        migrations.RemoveField(
            model_name='userprogressrecord',
            name='minutes_taken',
        ),
        migrations.RemoveField(
            model_name='userprogressrecord',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='userprogressrecord',
            name='questions_failed',
        ),
        migrations.AlterField(
            model_name='userprogressrecord',
            name='raw_mark',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
