# Generated by Django 4.1.7 on 2023-06-10 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examsolution', '0025_remove_userprogressrecord_hours_taken_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogressrecord',
            name='user',
        ),
    ]
