# Generated by Django 4.1.7 on 2023-06-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examsolution', '0027_userprogressrecord_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogressrecord',
            name='hours_taken',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprogressrecord',
            name='letter_grade',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='userprogressrecord',
            name='minutes_taken',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprogressrecord',
            name='percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprogressrecord',
            name='questions_failed',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
