# Generated by Django 4.1.7 on 2023-06-10 09:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('examsolution', '0028_userprogressrecord_hours_taken_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprogressrecord',
            options={'ordering': ['date_completed']},
        ),
        migrations.AddField(
            model_name='userprogressrecord',
            name='date_completed',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprogressrecord',
            name='percentage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
