# Generated by Django 4.1.7 on 2023-06-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examsolution', '0029_alter_userprogressrecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogressrecord',
            name='subject_of_paper_written',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
