# Generated by Django 4.1.7 on 2023-06-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examsolution', '0031_alter_userprogressrecord_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=200)),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_message', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='year',
            options={'ordering': ['-year']},
        ),
    ]
