# Generated by Django 4.1.7 on 2023-06-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examsolution', '0032_contactusinfo_alter_year_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullquestionanswer',
            name='google_drive_answer_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fullquestionanswer',
            name='google_drive_question_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
