# Generated by Django 4.1.7 on 2023-06-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examsolution', '0033_fullquestionanswer_google_drive_answer_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='question_google_drive_link',
            field=models.URLField(default='https://drive.google.com/file/d/1Io4Cr3F6rtz_RscCEgfznVawMlOfKI97/view?usp=sharing'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='answer_directory',
            field=models.FileField(blank=True, null=True, upload_to='TopicalAnswers'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='question_directory',
            field=models.FileField(blank=True, null=True, upload_to='TopicalQuestions'),
        ),
    ]
