# Generated by Django 4.1.7 on 2023-06-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examsolution', '0034_questionanswer_question_google_drive_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='question_google_drive_link',
            field=models.URLField(),
        ),
    ]
