# Generated by Django 4.1.7 on 2023-06-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examsolution', '0035_alter_questionanswer_question_google_drive_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='answer_google_drive_link',
            field=models.URLField(default='https://drive.google.com/file/d/1Io4Cr3F6rtz_RscCEgfznVawMlOfKI97/view?usp=sharing'),
            preserve_default=False,
        ),
    ]
