# Generated by Django 4.1.7 on 2023-06-17 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examsolution', '0036_questionanswer_answer_google_drive_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswer',
            name='answer_directory',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='question_directory',
        ),
    ]
