# Generated by Django 4.2.3 on 2023-08-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examsolution', '0037_remove_questionanswer_answer_directory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
